Repository njomeau/zuluzulu, pull requests merged in 2018-11, with the labels that each got.

#148 Dahn profile
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/ProfileFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/tequila/AuthServer.java
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: 0.5 day

#155 Dahn - Load associations ICONS and fill database
  .travis.yml
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/SettingsFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Structure/AssociationsUrlHandlerTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/URLTools/UrlHandlerTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/AssociationArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AboutZuluzuluFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/AssociationsUrlHandler.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/AssociationsParser.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/IconParser.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/Parser.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/Reader.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/UrlHandler.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/UrlReader.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/UrlReaderFactory.java
  app/src/main/res/layout/card_association.xml
  app/src/main/res/layout/fragment_association.xml
  app/src/main/res/layout/fragment_associations_generator.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/zuluzulu/URLTools/AssociationsParserTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/URLTools/IconParserTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/URLTools/UrlReaderFactoryTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/URLTools/UrlReaderTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/UserTest.java
Labels: 3 days

#165 Fix timeout and allow fragmentgenerator to write db #135
  .travis.yml
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragment.java
Labels: reformat code

#166 Near channels are visible
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/PostFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChannelArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/PostArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/SuperChatPostsFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Channel.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/ChatMessage.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Post.java
  app/src/main/res/drawable/channel_notclickable_background.xml
  app/src/main/res/layout/channel.xml
  app/src/main/res/layout/channel_toofar.xml
  app/src/main/res/layout/fragment_channel.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/post.xml
  app/src/test/java/ch/epfl/sweng/zuluzulu/ChannelTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/ChatMessageTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/PostTest.java
Labels: 0.5 day, new feature

#182 Dahn mock firebase
  .travis.yml
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/DocumentMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/FirebaseAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/FirebaseMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/CollectionAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/Database.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseCollection.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseDocument.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/FirebaseAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/DatabaseFactory.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragment.java
  app/src/main/res/layout/fragment_add_event.xml
  app/src/test/java/ch/epfl/sweng/zuluzulu/Firebase/DatabaseFactoryTest.java
Labels: 1 day

#184 Better code
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/DocumentMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/TaskMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragmentTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/EventArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/PostArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/CollectionAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseCollection.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/FirebaseAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/DatabaseFactory.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AboutZuluzuluFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/CalendarFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/SuperChatPostsFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Channel.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/ChatMessage.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/DateInputMask.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Event.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Post.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Utils.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/UrlReader.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/User/AuthenticatedUser.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/User/User.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/ImageLoader.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/tequila/AuthServer.java
  app/src/main/res/drawable/channel_background.xml
  app/src/main/res/drawable/channel_notclickable_background.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_event.xml
  app/src/main/res/layout/card_event.xml
  app/src/main/res/layout/channel.xml
  app/src/main/res/layout/channel_toofar.xml
  app/src/main/res/layout/chat_posts_buttons.xml
  app/src/main/res/layout/fragment_add_event.xml
  app/src/main/res/layout/fragment_association.xml
  app/src/main/res/layout/fragment_associations_generator.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_channel.xml
  app/src/main/res/layout/fragment_event.xml
Labels: reformat code

#191 Better IdlingResource
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestingUtility/TestWithUserAndFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/CommunicationTag.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/CalendarFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/IdlingResource/IdlingResourceFactory.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MementoFragment.java
  app/src/main/res/layout/fragment_memento.xml
Labels: enhancement

#192 Up and down posts
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/DocumentMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/WritePostFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/PostArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseDocument.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseMapDecorator.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/SuperChatPostsFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/WritePostFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Post.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Utils.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/PostColor.java
  app/src/main/res/layout/post.xml
  app/src/test/java/ch/epfl/sweng/zuluzulu/PostTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/Utility.java
Labels: 1 day, new feature

#198 Little update to posts
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/PostArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragment.java
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/post.xml
Labels: 0.5 day

#222 Load all events from memento and add to database #214
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MementoFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MementoFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Event.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventDate.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/MementoParser.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/UrlHandler.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/EventTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/Structure/EventDateTest.java
Labels: 2 days, enhancement

#224 Add event tests#214
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MementoFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Event.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/EventTest.java
Labels: enhancement

#226 Dahn EventBuilder
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/CalendarFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MementoFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Event.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventDate.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/URLTools/UrlHandler.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/EventTest.java
Labels: enhancement
