Repository njomeau/zuluzulu, pull requests merged in 2018-12, with the labels that each got.

#249 reformat
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/PostArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseMapDecorator.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxy.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Proxy.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/ProxyDependency.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AddEventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationsGeneratorFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/CalendarFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/EventDetailFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MementoFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Association.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Channel.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/ChatMessage.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Event.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventBuilder.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventDate.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/FirebaseStructure.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Post.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/User/AuthenticatedUser.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/User/User.java
Labels: reformat code

#247 Beautiful chat
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/PostArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ReplyFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/WritePostFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Post.java
  app/src/main/res/drawable/add_button.xml
  app/src/main/res/drawable/divider.xml
  app/src/main/res/layout/chat_message.xml
  app/src/main/res/layout/chat_message_noname.xml
  app/src/main/res/layout/chat_posts_buttons.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/values/colors.xml
Labels: 0.5 day

#275 Dahn save USER in SQL DATABASE
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestWithAdmin.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestWithAuthenticatedUser.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Utility.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MainFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabase.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseContract.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseHelper.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/AuthenticatedUserTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/TestingUtility/Utility.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/UserTest.java
Labels: 1 day

#277 Dahn change strings
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationFragmentAsAuthenticatedTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/EventDetailFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MenuAsGuestTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Utility.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/CollectionAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseCollection.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxy.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AboutZuluzuluFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#280 Chat message time
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ReplyFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/SuperChatPostsFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/SuperMessage.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/PostColor.java
  app/src/main/res/layout/chat_message.xml
Labels: 0.5 day

#285 Dahn tests - Mock proxy
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/DocumentMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/TaskMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxyTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/URLTools/UrlHandlerTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/AddAssociationAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/CollectionAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseCollection.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DatabaseDocument.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/OperationWithFirebaseMap.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Database/OperationWithFirebaseMapList.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseMapDecorator.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxy.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseContract.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventDate.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/Utils.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/AuthServerTest.java
Labels: 0.5 day

#293 Better association details layout
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragmentTest.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragment.java
  app/src/main/res/layout/fragment_association_detail.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_event_detail.xml
  app/src/main/res/layout/fragment_reply.xml
  app/src/main/res/layout/fragment_write_post.xml
  app/src/main/res/values/strings.xml
Labels: 1 day

#295 General improvement
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/CollectionMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/DocumentMock.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/Database/DocumentAdapterTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxyTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChangeUserRoleFragmentAsAdminTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/EventDetailFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragmentAuthTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/EventFragmentGuestTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/MainFragmentGuestUserTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ReplyFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabaseTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestingUtility/TestWithUserAndFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChannelArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/ChatMessageArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxy.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AssociationDetailFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChannelFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ChatFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MainFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/Channel.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/EventDate.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Structure/GPS.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/Utils.java
  app/src/main/res/drawable/add_post.png
  app/src/main/res/drawable/chat_background.png
  app/src/main/res/drawable/chat_message_background.xml
  app/src/main/res/drawable/chat_message_background_ownmessage.xml
  app/src/main/res/drawable/chat_message_edit_background.xml
  app/src/main/res/drawable/send_message.png
  app/src/main/res/layout/chat_message.xml
  app/src/main/res/layout/chat_posts_buttons.xml
  app/src/main/res/layout/fragment_association.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/post.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/ch/epfl/sweng/zuluzulu/Structure/EventBuilderTest.java
  app/src/test/java/ch/epfl/sweng/zuluzulu/Structure/EventDateTest.java
Labels: enhancement

#291 Fix login
  .travis.yml
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxyTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/MainFragmentGuestUserTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/PostFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ReplyFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LoginTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MainActivityListenerTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MementoFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Utility.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/CommunicationTag.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxy.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Firebase/Proxy.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AdminFragments/AdminPanelFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AdminFragments/MementoFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/SuperChatPostsFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/WebViewFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_webview.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sweng/zuluzulu/Structure/EventDateTest.java
  gradle/wrapper/gradle-wrapper.properties
Labels: 2 days

#298 Improve login layout Dahn
  .idea/assetWizardSettings.xml
  .idea/dictionaries/Nicolas.xml
  .idea/dictionaries/n98_main.xml
  .idea/inspectionProfiles/Project_Default.xml
  .travis.yml
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/AboutZuluzuluFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Database/MockedProxy.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Firebase/FirebaseProxyTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragmentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/LoginTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MainActivityIntentTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MenuAsAuthenticatedTest.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestWithAdmin.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestWithAuthenticatedUser.java
  app/src/androidTest/java/ch/epfl/sweng/zuluzulu/TestingUtility/TestWithUserAndFragment.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sweng/zuluzulu/Adapters/EventArrayAdapter.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/AdminFragments/MementoFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/EventDetailFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/LoginFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/MainFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Fragments/ProfileFragment.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/LocalDatabase/UserDatabase.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/MainActivity.java
  app/src/main/java/ch/epfl/sweng/zuluzulu/Utility/Utils.java
  app/src/main/res/drawable/ic_add_a_photo_black_24dp.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
Labels: 2 days
